### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by Serenity8888**
Update

### CODE REVIEW

**Comment by Serenity8888** [comment]
update

**Review by aynjel — COMMENTED** [review]
dev

**Review by Serenity8888 — COMMENTED** [review]
Update footer

**Review by Serenity8888 — COMMENTED** [review]
Update moviecard

**Review by Serenity8888 — COMMENTED** [review]
Update movie card

**Review by aynjel — COMMENTED** [review]
done review

**Review by Serenity8888 — COMMENTED** [review]
Update movie card

**Review by Serenity8888 — COMMENTED** [review]
Update movie card and modals

**Review by Serenity8888 — COMMENTED** [review]
Update

**Review by Serenity8888 — COMMENTED** [review]
Update moviecard

**Review by Serenity8888 — COMMENTED** [review]
Update

**Review by aynjel — COMMENTED** [review]
done review

**Review by Serenity8888 — COMMENTED** [review]
Update

**Review by Serenity8888 — COMMENTED** [review]
Update footer

**Pull request merged**
